server:
  port: 7688

eureka:
  instance:
   # hostname: localhost
#    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8990/eureka/
