server:
  port: 8990

eureka:
  instance:
   # hostname: localhost
   # prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:7688/eureka/

